CREATE OR REPLACE FORCE VIEW DWH_BV.MC_ACTIVITY 
AS 
SELECT
        H1.MCACT_SK        MCACT_ID,
        H1.MCACT_BK        MCACT_INTEGRATION_ID,
        L1.MCACT_PRD_SK    MCACT_PRD_ID,
        L1.MCACT_RETP_SK   MCACT_RETP_ID,
        L1.MCACT_CUS_SK    MCACT_CUS_ID,
        L1.MCACT_ACT_SK    MCACT_ACT_ID, 
        S1.MCACT_NAME,
        S1.MCACT_START_DT,
        S1.MCACT_STATUS,
        S1.MCACT_CLICK_CNT,
        S1.MCACT_OPEN_CNT,
        S1.MCACT_CAMPAIGN_ID,
        S1.MCACT_CAMPAIGN_NAME,
        S1.MCACT_CAMPAIGN_DESC,
        S1.MCACT_PRD_DETAILS,
        S1.MCACT_PROGRAM_NAME,
        S1.MCACT_PROGRAM_DESC,
        S1.MCACT_RECORD_TYPE_NAME,
        S1.MCACT_REGION,
        S1.DWH_SRC_SYSTEM,
        S1.DWH_RUN_ID,
        S1.DWH_LOAD_START_TS
		FROM       DWH_DV.MC_ACTIVITY_H H1
        INNER JOIN DWH_DV.MC_ACTIVITY_L      L1 ON H1.MCACT_SK = L1.MCACT_SK
        INNER JOIN DWH_DV.MC_ACTIVITY_S_MCRM S1 ON H1.MCACT_SK = S1.MCACT_SK
;