CREATE OR REPLACE VIEW DWH_BV.VAE_TEMPLATE AS
SELECT
  H1.VAET_SK 		VAET_ID
, H1.VAET_BK 		VAET_INTEGRATION_ID
, VAET_PRD_SK 		VAET_PRD_ID
, VAET_PAR_PRD_SK 	VAET_PAR_PRD_ID 
, (SELECT RETP_NAME FROM DWH_BV.RECORDTYPE WHERE RETP_ID= VAET_RETP_SK) VAET_RETP_NAME
, VAET_EMAIL_SUBJECT
, VAET_STATUS
, FIRST_VALUE(VAET_NAME) IGNORE NULLS OVER (PARTITION BY VAET_VAULT_DOCUMENT_ID ORDER BY H1.VAET_SK DESC ) AS VAET_NAME
, VAET_NAME VAET_NAME_PREV
, VAET_DESC
, VAET_VAULT_DOCUMENT_ID 
, VAET_VAULT_INSTANCE_ID 
, VAET_DOCUMENT_ID
, VAET_ALLOWED_DOCUMENT_IDS
, H1.DWH_SRC_SYSTEM
FROM DWH_DV.VAE_TEMPLATE_H H1
INNER JOIN DWH_DV.VAE_TEMPLATE_L L1 		ON H1.VAET_SK = L1.VAET_SK
INNER JOIN DWH_DV.VAE_TEMPLATE_S_MAIN S1     ON H1.VAET_SK = S1.VAET_SK
INNER JOIN DWH_DV.VAE_TEMPLATE_S_TAIL S2     ON H1.VAET_SK = S2.VAET_SK
--WHERE VAET_VAULT_DOCUMENT_ID = '10098'
ORDER BY VAET_VAULT_DOCUMENT_ID
;
