CREATE OR REPLACE VIEW DWH_BV.VAE_CONSENT AS
SELECT H1.VAECON_SK VAECON_ID 
,H1.VAECON_BK VAECON_INTEGRATION_ID
, H1.DWH_SRC_SYSTEM
, VAECON_CUS_SK VAECON_CUS_ID
, VAECON_VAECOT_SK VAECON_VAECOT_ID
, VAECON_CAPTURED_EMP_SK VAECON_CAPTURED_EMP_ID
, COALESCE ( VAECON_DT,VAECON_SIGN_DT) VAECON_DT
, VAECON_CHNL_VALUE
, VAECON_OPT_EXPIRATION_DT
, VAECON_OPT_SRC
, VAECON_OPT_TYPE
, VAECON_OPT_EVENT_TYPE
, S2.VAECON_SRC_UPDATE_BY
, S2.VAECON_SRC_CREATE_BY
, S2.VAECON_DUO_ID
, S2.VAECON_CHNL_KEY
, S2.VAECON_CHNL_SRC
, S2.VAECON_CHANGE_REASON
, S1.DWH_RUN_ID
, S1.DWH_CREATE_DATE
, S1.DWH_UPDATE_DATE
FROM DWH_DV.VAE_CONSENT_H H1
INNER JOIN DWH_DV.VAE_CONSENT_L L1 		ON H1.VAECON_SK = L1.VAECON_SK
INNER JOIN DWH_DV.VAE_CONSENT_S_MAIN S1 ON H1.VAECON_SK = S1.VAECON_SK
INNER JOIN DWH_DV.VAE_CONSENT_S_TAIL S2 ON H1.VAECON_SK = S2.VAECON_SK
INNER JOIN DWH_DV.VAE_CONSENT_S_SIGN S3 ON H1.VAECON_SK = S3.VAECON_SK
;
